### ISSUE TITLE
Internal Images in Vaults

### ISSUE THREAD

**Issue by sigrunixia** [carlonicora/obsidian-rpg-manager#179]
This is a possible bug report from OmegaLz on Discord. 

This is also a documentation need on my end, as our files currently lack anything on images. 

## Summary
Clarification is needed on the current functionality of image calling within RPGM. 
1. There was a function in prior versions where an Attachments folder + the image file being named as the same as the relevant component sheet, would display the image. Does this functionality still exist? If so, it appears to not be working. 
2. What is the preferred way to link to images from within the vault, and are there any limitations? 
3. Does the vault need to be set up in a certain manner? For example, will RPGM respect a markdown link the same as a wiki link? An absolute path link the same as a relative path link?

### Possible Bug Report
After OmegaLaz reported it, I tried linking to an image in my vault using every combination of wiki link and non wiki link. Relative path, absolute path. Direct linking. External links work fine. 

I confirmed via developer tools that the url to the file is correct, but it is not being read by RPGM. Only error message is:
`Failed to load resource: net::ERR_FILE_NOT_FOUND`

**Comment by carlonicora** [comment]
@sigrunixia The bug was related to how the YAML in `RpgManagerData` is created. It has been fixed and will be released as part of `v3.0.1`

### Expected behaviours for images

In the `RpgManagerData` codeblock the `image` attribute can have the following states and results:

|image attribute value|expected result|v3.0|v3.0.1|
|---|---|:---:|:---:|
|empty|If present, display the file `Attachment` folder with the same name as the note|✓|✓|
|null|If present, display the file `Attachment` folder with the same name as the note|**✗**|✓|
|""|If present, display the file `Attachment` folder with the same name as the note|✓|✓|
|a valid url|Fetches the image from the provided url|✓|✓|

### Next steps

I will leave this issue open to keep it in the radar for the documentation

**Comment by carlonicora** [comment]
Closing as documentation will be added to #168
