### ISSUE TITLE
Propose a different name for `component`

### ISSUE THREAD

**Issue by carlonicora** [carlonicora/obsidian-rpg-manager#199]
## Scope

There is a clash of business and technology naming convention: both uses `component`

### Current Actions

The current naming convention defines a `component` as the element of RPG Manager (_Campaign, Character, Act, ..._). Unfortunately, the same naming convention would be extremely useful in the code, and both can't live at the same time.

### Suggested Actions

Change the business naming convention of `component`. @sigrunixia do you have any suggestion?

## Context or Use Case

<**As a**> RPG Manager maintainer
<**I want to**> use the keyword `component` for development purpose
<**So that**> I can make it simpler for additional developers to propose changes

**Comment by sigrunixia** [comment]
I am trying to think of a word we would never have to or want to use elsewhere, but would also be understood contextually even if not on the outset to mean "multiple small groups of things."

I think the obscure word we can use is "Parcel."

Dictionary results:
**par·cel** | ˈpärs(ə)l |
noun
1 a thing or collection of things wrapped in paper in order to be carried or sent by mail: a brown paper parcel | [as modifier] : a parcel bomb.
2 a quantity or amount of something, especially as dealt with in one commercial transaction: a parcel of shares.
• a piece of land, especially one considered as part of an estate: she decided to divide her property into three parcels and invite sealed bids.
• technical a portion of a larger body of air or other fluid considered as a discrete element: an inversion forms a barrier to a rising parcel of air.
verb (parcels, parceling, parceled; British parcels, parcelling, parcelled) [with object]
1 make (something) into a parcel by wrapping it: he parceled up the goods and sent them back.
• (parcel something out) divide into portions and then distribute: they will start parceling out radio frequencies for digital cordless telephones.
2 Nautical wrap (rope) with strips of tarred canvas, before binding it with yarn as part of a traditional technique to reduce chafing.
**PHRASES**
pass the parcel | ˌpas T͟Hə ˈpärsəl |
a children's game in which a parcel is passed around to the accompaniment of music, the child holding the parcel when the music stops being allowed to unwrap a layer.
**ORIGIN**
late Middle English (chiefly in the sense ‘small portion’): from Old French parcelle, from Latin particula ‘small part’.

Thesaurus:
parcel
**noun**
1 a parcel of food and clothes: package, packet; pack, carton, bundle, box, case, bale; archaic fardel.
2 a 21-acre parcel of land: plot, piece, patch, tract, area, section, allotment; North American lot, plat.
3 a parcel of rogues: group, band, pack, gang, crowd, mob, company, collection, horde, party, troop; informal crew, bunch.
**verb**
1 she parceled up the papers: pack, pack up, package, wrap, wrap up, gift-wrap, tie up, do up, box, box up, bundle up, fasten together.
2 parceling out commercial farmland in small plots will reduce productivity: divide up, portion out, distribute, share out, allocate, allot, apportion, hand out, give out, deal out, dole out, mete out, dispense, split up, carve up; informal divvy up, dish out.

**Comment by sigrunixia** [comment]
Some other suggestions that came from Carlo directly were **Record** and **Element**. 

Record can be tied to both the existing music and overall writing features. 
Nearly everything is an element already, colloquially.

**Comment by sigrunixia** [comment]
Playing with the dictionary some more. Oxford. Taking the closest definition to our use case. I also grabbed the "recommended synonyms" for each definition.

**Element**: _a part or aspect of something abstract, especially one that is essential or characteristic: the death had all the elements of a great tabloid story | there are four elements to the proposal._

Recommended Synonyms: Rudiment. Integrant. Ingredient. 

**Record**: 
N. _a thing constituting a piece of evidence about the past, especially an account kept in writing or some other permanent form: you should keep a written record | identification was made through dental records | a record of meter readings._
V. _(of an instrument or observer) show or register (a measurement or result): the temperature was the lowest recorded since 1926._

Recommended Synonyms: Chronicle. 

**Rudiment**: N. _1 (the rudiments of) the first principles of (a subject): she taught the girls the rudiments of reading and writing.
• an elementary or primitive form of something: the rudiments of a hot-water system._

No recommended Synonyms

**Integrant**: N. _a component: the scenes function as dramatic integrants._

No Synonyms

**Chronicle**: V. _record (a related series of events) in a factual and detailed way: his work chronicles 20th-century displacement and migration._

No recommended synonyms

**Ingredient**: N. _a component part or element of something: the affair contains all the ingredients of an insoluble mystery._

Recommended Synonyms: Integrant

---

So there we go. Out of those I do like Element, Integrant, and Ingredient the best as options.
