### ISSUE TITLE
Exploration: Clean Uninstall

### ISSUE THREAD

**Issue by sigrunixia** [carlonicora/obsidian-rpg-manager#200]
## Scope

Query into seeing if it is possible to fix leftover contamination of note data after removal of RPG Manager.

## Current Actions

When RPG Manager is disabled and uninstalled, the code blocks and all other RPG Manager Data remains in the note. If someone has a very large campaign and wants to remake it, or decides RPGM is not for them and wants to use something else, they will need to spend some time on cleanup.

## Suggested Actions
This is currently normal behavior for plugins that utilize code blocks, such as Dataview and Admonitions. Once the plugin is disabled, RPG Manager is unable to act. However, there may be something that can be done while the plugin is active. 

- Create a clean-notes protocol to remove all of RPG Manager's data from some or all of the vault. It only removes the code-blocks and associated data to maintain those code-blocks. 

## Context or Use Case

<As a> RPG Manager Collaborator and User
<I want to> Provide the option to clean notes of the RPG Manager Codeblocks and associated RPG Manager Data
<So that> Users who of RPG Manager who use this option can return their notes to a plugin-free state
<And> This can be adopted across other plugins that do the same thing.
<Therefore> Fulfilling the user-plugin implicit contractual arrangement.

**Comment by carlonicora** [comment]
Hi @sigrunixia 

Unfortunately, there is nothing we can do on that.
The only moment in which RPG Manager can do something is when a user deactivates the plugin, but it can only be something done automatically, not with a user-interface. This is because once the user switches off the plugin, I am given (_I think_) one last function I can use, but at that time, the plugin is switched off completely.

During the deactivation, I would not delete or change anything. Consider for an instant: I may deactivate the plugin for whatever reasons, and if I activate it back, I expect all my data to be there. Also, if you install your vault on a mobile, sometimes the plugins gets deactivated pending user confirmation, what would happen in that case?

Of course, no plugin has any control when it is deleted, so I cannot trigger any event at that stage.

In this instance, I would not keep this into consideration. The data will remain there and they will be very visible in the notes (_the code blocks won't render the views any longer, and they will be shown as text_).

Fiddling with data when a user decides to leave is a dangerous business...
