### ISSUE TITLE
[BUG] My custom templates for NPCs and PCs didn't update with the Updater

### ISSUE THREAD

**Issue by cjolson** [carlonicora/obsidian-rpg-manager#216]
## Scope

I've been using custom templates when making NPCs and PCs, but they didn't get updated with the update. I have about 100 files to update, so I'm curious if there is a clear fix since editing them manually will be very tedious.

### To Reproduce

I attempted a reinstall of the plug-in to trigger the updater again. After the updater completed the update, my NPCs and PCs still did not update.
 
### Expected behaviour

I would expect the NPC and PC files to update. Below are two newly created NPC files post-update using both the default and my custom template.
[Test (Default Template).md](https://github.com/carlonicora/obsidian-rpg-manager/files/9844716/Test.Default.Template.md)
[Test (Custom Template).md](https://github.com/carlonicora/obsidian-rpg-manager/files/9844717/Test.Custom.Template.md)

### Screenshots

- Here is an example of an NPC that did not update: [Floon Blagmaar.md](https://github.com/carlonicora/obsidian-rpg-manager/files/9844720/Floon.Blagmaar.md)
- This one is a file for PC that did not update: [Edrom.md](https://github.com/carlonicora/obsidian-rpg-manager/files/9844723/Edrom.md)
- Here are my custom templates for both: [New NPC.md](https://github.com/carlonicora/obsidian-rpg-manager/files/9844726/New.NPC.md) and [New PC.md](https://github.com/carlonicora/obsidian-rpg-manager/files/9844725/New.PC.md)

### Additional context
As far as I can tell, all my other files updated correctly. Only NPCs and PCs seem to have the problem. Nearly all of my files use a custom template too, but these are the only ones that had a problem.

**Comment by cjolson** [comment]
@carlonicora, in thinking on it, it’s possible that the source of this bug was a specific NPC who had quotes in the title of the note? Would that have caused the updater to stop and not update the files that followed (in my cased other NPCs and the PCs). 

I’ve noticed the quotations in the file name created other issues in the manager (particularly with images) so I removed them.

**Comment by carlonicora** [comment]
Hi @cjolson 

Yes, the `root of all evil` are badly formatted YAML. When you run the updater, you will notice that there are errors in the console. If you find the element with the specified error you will find that some information in the `RpgManagerData` will contain one of the following:

- unescaped double quotes (For example: `synopsis: "This is the "synopsis""` -> remove the unescaped double quotes)
- carriage returns
- Strings not written in between double quotes starting with [[

If you check it, you will be able to upgrade by fixing a few notes

**Comment by cjolson** [comment]
@carlonicora , the update actually completed (just without doing the any of the NPC or PC files). I’m not certain why those files were skipped during the update, but it’s been more than a week since I updated so I’m not sure if I can see what errors it threw at the time.

I’ve since fixed the files manually, so my troubleshooting is more for future updates. The YAML for all those files looked fine, but the first NPC in my NPC folder was had the title `”Bonnie”.md`. I’m curious if you think the quotation marks in the file title may have broken something in the updater and caused it to crash before it updated the NPCs and the PCs?

**Comment by carlonicora** [comment]
@cjolson I am not entirely sure about the double quotes on the filename. That is something managed entirely by Obsidian, and did not have a valid test. Will look into it

**Comment by sigrunixia** [comment]
Obsidian allows single and double quotes in a filename (which I disagree with, but thats just me). 

Top of mine, I think the issue would come in with quotes is this situation:

---

`yaml-key: path/to/"file".md`

With the latest update and the addition of the gallery manager, the removal of images yaml-key to add a link to image yamlk-key, meant somewhere in RPGM, the updater had to isolate that yaml-key and remove it. 

`"yaml-key: path/to/"file".md"` or `"yaml-key: "path/to/"file".md""`

YAML is very, very picky about how quotation marks ought to be applied. In order to process this right, the lines above need to look like this instead. A backslash is used in YAML to "escape" a character and tell YAML to "ignore" it, in simplest terms. 

`"yaml-key: path/to/\"file\".md"` or `"yaml-key: \"path/to/\"file\".md\""`

However, you cannot apply a \ in a filename normally even by Obsidian's Standards, so the updater would have need to know to apply the \ in its updater and would have needed to know exactly where to apply it. 
Secondly, not all systems/languages allow the use of ' and " in filenames, which is why I am against Obsidian allowing it. Michigan Tech keeps a list here of [characters to avoid](https://www.mtu.edu/umc/services/websites/writing/characters-avoid/) in filenames. 

---

It could have been this, it could not be. There is no blame to assign beyond being somewhat annoyed at Obsidian coding for allowing the filename because its not the first time some characters have caused issues. However, it's a feature in some views, so we work with what we have.

**Comment by cjolson** [comment]
Thanks so much! I’m definitely leaning towards that being the issue from the update, so I can close this thread. If I run into issues on future updates, I’ll let you know. I appreciate it!
