### ISSUE TITLE
Templates in the New RPGM

### ISSUE THREAD

**Issue by sigrunixia** [carlonicora/obsidian-rpg-manager#217]
Leaving this open for general Q&A.

Templates as an option for RPGM were created back when RPGM stuck all of its data into the Frontmatter. Now, RPGM no longer does so, and relies on code blocks and modules.

## Some questions to ponder and answer

How would you like to see templates utilized going forward? 

How are you currently adding templates to RPGM?

Have any updates broken any of your templates?

Any other feedback from a user and developer standpoint?

### Related Topics
- #161

**Comment by cjolson** [comment]
I use templates a lot still for a few use cases:
- I have certain formats for how I structure the notes for specific components. My NPC template contains specific sections for each NPC.
- There is some metadata I like to include in certain notes for non-RPG Manager reasons. For example, PCs require some metadata for the Initiative Tracker plug in (level, hp, ac, and initiative).
- I have my own template for each component which I select in the modal every time I make a component.

Somethings I'd love:
- I wish I could chose my own templates as the default for each component. I frequently forget to change it when using the Fill or Create command which is somewhat annoying. 

Issues:
- #216 is my only issue with templates. For some reason the updater for v3 didn't work on the NPCs and PCs I had (maybe due to the custom templates). The templates do work as expect if I remake the component using the Fill or Create command and select it though.

**Comment by sigrunixia** [comment]
#264

**Comment by sigrunixia** [comment]
We've gathered much of the answers to this in the ongoing survey. Closing this thread.
