### ISSUE TITLE
3.4 Issues

### ISSUE THREAD

**Issue by Sweet0-0** [carlonicora/obsidian-rpg-manager#271]
I'm working on an android device and it' not updating the notes or allowing new ones and the stat blocks on the notes aren't working anymore

**Comment by carlonicora** [comment]
Hi @Sweet0-0 

Thanks for the report.
I can see that there is an issue using Fantasy Calendar on mobile, but the rest works for me on iOS.

I had to reload the application twice to make sure all the data was correctly synced. Can you take a video of the issue for me to look at?

Thanks
Carlo

**Comment by Sweet0-0** [comment]
Uploading petal_20221206_165711.mp4…

**Comment by Sweet0-0** [comment]
How can I send you a video. For some reason they don't send on gethub or Email

**Comment by Sweet0-0** [comment]
> How can I send you a video. For some reason they don't send on gethub or Email

Okay! I sent you a few short videos showing the program not working on you're Email as I can't send it here hope it helps

**Comment by carlonicora** [comment]
Hi @Sweet0-0 

Thanks for sending the videos. In one of them I can see that the upgrade does not work. I never tried an update directly on mobile, but I will check it asap

In another video, you can see that RPG Manager is not active (_probably because it didn't update_) as you can see the name of the code block on the right (_that is the hint that the plugin is not active_).

As for the campaign not creating... that baffles me, and I will look into it. My bet is about the filesystem adapter... I will dig into it

**Comment by careilly** [comment]
I’ve got a similar problem on an iPad and iPhone on which the plug-in seems to be working perfectly in a different vault at the same version.

**Comment by careilly** [comment]
Uninstalling and reinstalling gives me this:

[info] Loading RpgManager 3.4.4 
[warn] Updating RPG Manager from v3.0 to v3.1
[warn] Updating RPG Manager from v3.1 to v3.4

And campaign creation fails silently, creating a location in an existing campaign closes the modal but does not create the note.

**Comment by careilly** [comment]
I fixed the behaviour by deleting all the RPG Manager info from my locations and redoing them: the problem eventually propagated back to Obsidian on my Mac and I could see in the console that there was an error to do with building location relationships. It's possible just deleting them would have sorted the problem out.

**Comment by Sweet0-0** [comment]
I don't think that's my problem, I only have a Campaign note in the vault I have the update it

**Comment by careilly** [comment]
Possibly not. But it looked the same initially. 

I've never succeeded in an update on mobile either - I've had to do that on desktop.

**Comment by sigrunixia** [comment]
I sincerely apologize for the radio silence. Carlo is mid-move and I have been having construction done in my flat. 

For All Cases:
We'll need to take a closer look at what is happening on on the scripting side in mobile when @carlonicora finishes his move (which also required a change in ISP). 

For @careilly 
I'm glad you were able to fix it by recreating it. That makes me think there was a piece of information the updater may have failed to convert over, or there was a YAML code block issue. Historically, the biggest incidences involved some malformed YAML in a code block at some point, such as quotation marks or certain special characters within the code block (and once within the file name itself), which makes the modal no longer render. This is behavior that _may_ no longer be an issue in Obsidian 1.1 due to the way YAML is read, written, and modified by plugins. But that remains to be seen. 

If it's an updater issue, @x1101 has been looking into that side of things. 

@Sweet0-0
Do you have a backup of your vault pre-update, and were you on 3.3 before updating to 3.4?

**Comment by Sweet0-0** [comment]
I do have one I think it's 3.2.4. I'm working on it in my main campaign

**Comment by carlonicora** [comment]
@Sweet0-0 @sigrunixia @careilly I think I have found and solved the issue.

Obsidian mobile does not support all the crypto functions I added in 3.4 and therefore it was stopping the execution of the code when hitting the new IDs.

I have now released 3.4.5 with a fix for it. Please do let me know if it is working. For the time being I will close this as in my iOS everything is smooth!
