### ISSUE TITLE
Issue with multiple fantasy calendars per Vault[BUG]

### ISSUE THREAD

**Issue by Afterburner0** [carlonicora/obsidian-rpg-manager#279]
## Scope

I am running the latest version of Obsidian, Fantasy Calendar, and RPG Manager. I have multiple campaigns in the same Vault. I am able to successfully integrate a fantasy calendar into one campaign. I can also integrate that same calendar into multiple campaigns. However, when the same calendar is used in multiple campaigns, and I change the "Current Date" in campaign "A," the current date also changes in campaign "B" without my input.

### To Reproduce

Steps to reproduce the behaviour:
1. Create two campaigns, campaign A and campaign B.
2. In the Fantasy Calendars plugin, import one fantasy calendar (Calendar A) from a json file.
3. Integrate calendar A into campaign A and campaign B.
4. Close Obsidian and reopen.
5. Modify the Current Date of calendar A in the note for campaign A.
6. Close Obsidian and reopen.
7. The date automatically modifies in campaign B also.

### Expected behaviour

The fantasy calendar date in campaign B should not synchronize with campaign A's calendar date when I change the fantasy calendar date in campaign A.

### Desktop

 - OS: Windows 10

### Additional context

Here's what I've done for troubleshooting: I have created a second, separate fantasy calendar (Calendar B), exported it as a json file, imported it into the obsidian fantasy calendar plugin. After importing calendar B, closing Obsidian and reopening it, the "Current Date" line in both notes for campaign A and B disappear entirely. I have also tried making sure the original Gregorian calendar date in each note was different before integrating the fantasy calendars. Nothing seems to work.

**Comment by sigrunixia** [comment]
Carlo may have an idea for a fix, but I suspect this is what is happening using an example:
- Currently in FC-Calendar, you have one crazy intercalary Calendar named Taco.
- In campaign A, you may be having Taco in the year 5283-taco
- In campaign B, you may be having Taco in the year 00000t00c000a000c001taco
- Campaign A adds event to the Taco Calendar.
- As Campaign B is also using the same Taco Calendar, it adds it as well because there is only one calendar in FC-Calendar.

Category Quick Fix: If you do not have interaction between Campaign A and B as far as events, the fix is to duplicate calendar Taco in FC-Calendar, give it a new name, and assign it to Calendar B as Taco-2.
Category Slow Fix: If you do have interaction between between Campaign A and B as far as events and dates, then it gets more complicated. 

Which category do you fall into, @Afterburner0?

### Slow Fix
Carlo _might_ be able to insert a fix where it generates unique event categories per campaign, but that gets very messy and is more of a _hack_ than a solution. 

The solution may be more on FC-Calendar's end, which they are beginning to work on a rewrite of the plugin, and this can be functionality we request they support. 

What do you think @carlonicora? If it's a FC problem, I'll reach out to them and see if we can get it on their radar.

**Comment by Afterburner0** [comment]
Thank you for the response! I think I fall under the "Quick Fix" category. But duplicating the calendar and renaming it does not seem to be working. I don't need interaction between campaigns A and B. I think I see you in the Obsidian Discord server. If you want, I could add you, share my screen to you and and show what's happening. It may be easier than me trying to describe the issue with text alone.

**Comment by carlonicora** [comment]
Hi @Afterburner0 

You have to consider a Fantasy Calendar as a physical calendar. When you change the "current date", it's like you are writing it on the physical calendar.
When more than one campaign share the same calendar, it is impossible to set the current date for both.

This is not a limitation of RPG Manager, but it is how Fantasy Calendar works, and it is a limitation we have to abide to.

In your case, you don't have one fantasy calendar, but two (seen that the two campaigns do not interact with each other). To make it work just duplicate the fantasy calendar and you are good to go.

### Example:
Campaigns
- Dragonlance: The War of the Lance
- Dragonlance: The War of Soul

Original Fantasy Calendar
- _Ansalon Calendar_

Fantasy Calendar Solution
- _Calendar of The War of the Lance_ (Duplicated from _Ansalon Calendar_)
- _Calendar of The War of the Soul_ (Duplicated from _Ansalon Calendar_)

Hope this helps!

Carlo
