### ISSUE TITLE
[Bug]: Graph not showing relationship links

### ISSUE THREAD

**Issue by Jackson98Tomphson** [carlonicora/obsidian-rpg-manager#317]
### Check for existing bug reports before submitting.

- [X] I searched for existing Bug Reports and found no similar reports.

### Expected Behavior

I've tried to link with Add Relationships a link between characters and locations, but It doesn't show any link on the graph between entities. I've tried also to add a .md link on my own, and even if it does show the link mention and I can click on it too, no arch of any link I've done shows on the graph. I'm doing it wrong or there is a setting in the plug-in that prevents those kind of links?

### Current behaviour

About the Add Relationship bug:
![image](https://github.com/carlonicora/obsidian-rpg-manager/assets/48087046/847cc005-dc30-4fb4-902a-80e1edbec1ca)

Here's the graph:

![image](https://github.com/carlonicora/obsidian-rpg-manager/assets/48087046/a2c39889-53fd-48ab-94f2-2066a69993a7)

About the Reference Link Bug:
![image](https://github.com/carlonicora/obsidian-rpg-manager/assets/48087046/faca4f55-2be7-4fd1-95be-98a6e16f41dd)

Here's the graph:

![image](https://github.com/carlonicora/obsidian-rpg-manager/assets/48087046/d172be21-d312-44fb-8358-bcdc0f118dcd)

### Reproduction

For the Add Relationship Bug:
1. Create Campaign
2. Create Locations
3. Create Character
4. Add Relationship of any kind
5. Visualize the graph

For the Reference Link Bug:
1. Create Campaign
2. Write Description text
3. Add link with [[]] classic markdown of obsidian
4. Visualize the graph

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [X] Windows

### Obsidian Version Check

1.4.16

### Plugin Version

4.1.4

### Confirmation

- [ ] I have disabled all other plugins and the issue still persists.

### Possible solution

Maybe it's a problem in the command Add Relationships that doesn't always add the reference link? But it wouldn't explain the second bug. Here's a list of plug-ins I use, but there shouldn't be any interference:
![image](https://github.com/carlonicora/obsidian-rpg-manager/assets/48087046/f5ffc18a-7d44-4920-a4cb-67d5297e3a3b)

**Comment by carlonicora** [comment]
Hi @Jackson98Tomphson 

Let me see if I can get some more info to debug this. In the `Kyle O'Donnel` you should find a hidden link to the `Le Terre Nuove` at the bottom of the file. You will probably have to go with your cursor at the bottom of the file.
Check if the link is there.

Please note that in order to make the graph work, I need to `hack` the way the relationships are created, adding the links manually and hiding them (otherwise Obsidian does not see them).

as or linking another element, is `D&D 5e.md`a RPG Manager element or a simple note? I am not sure I can make it work with normal notes. The reason is the same as above. The data you add are stored in a codeblock, and obsidian does not read the links inside codeblocks, but adding the link there would be harder than the links to other non-rpgm files.

Let me know about the `Kyle O'Donnel` file and I will see what the issue can be

**Comment by carlonicora** [comment]
@Jackson98Tomphson Typescript is similar to C#.
If you want I can show you around the codebase (and if you like we can speak Italian) :D

...every little helps!

**Comment by Jackson98Tomphson** [comment]
Yeah sure! (I've used English only for external anglophone users 🤣) You can contact me on my Discord account on my githun profile
